### ISSUE TITLE
TensorFlow with Arabic Bert

### ISSUE THREAD

**Issue by Rababalkhalifa** [alisafaya/Arabic-BERT#4]
Thanks for the great work with ArBert.

I have been doing an experiment with the model but I got the following error:

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/training.py:571 train_function  *     
    outputs = self.distribute_strategy.run(     <ipython-input-108-063d7a7dce6a>:46 call  *       
  x = self.embed_with_bert(inputs)     <ipython-input-124-2e2afaeeb28c>:39 embed_with_bert  *      
   embds = self.bert_layer(all_tokens[:,0,:],     /usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py:550 __call__  *    
     result = self.forward(*input, **kwargs)     /usr/local/lib/python3.6/dist-packages/transformers/modeling_bert.py:691 forward  *   
      input_shape = input_ids.size()     AttributeError: 'Tensor' object has no attribute 'size'

I have used same thing for English bert from hub and huggingface and worked find but not for the Arabic version. Please let me know if you found something missing ?

**Comment by alisafaya** [comment]
Hi @Rababalkhalifa , 

Unfortunately I couldn't run your code, since I don't have the dataset you are using in my drive. But I reviewed your code; I think you should encode your tokenized data into tensorflow tensors directly:

```python
t = tokenizer.batch_encode_plus(sentences,
                        pad_to_max_length=True,
                        add_special_tokens=True,
                        max_length=55,
                        return_tensors='pt')
```

to

```python
t = tokenizer.batch_encode_plus(sentences,
                        pad_to_max_length=True,
                        add_special_tokens=True,
                        max_length=55,
                        return_tensors='tf')
``` 

See: [batch_encode_plus](https://huggingface.co/transformers/main_classes/tokenizer.html#transformers.PreTrainedTokenizer.batch_encode_plus)

By doing this you will not need to `detach()` part and convert the encoded tokens into `np.array`. 
You will be able to use them directly with the model.

**Comment by Rababalkhalifa** [comment]
Many thanks. This is very helpful!!

but now I am getting; AttributeError: 'list' object has no attribute 'size'

is this format correct:

embds = self.bert_layer([all_tokens[:,0,:],
                                   all_tokens[:,1,:],
                                   all_tokens[:,2,:]])

or 

embds = self.bert_layer(all_tokens[:,0,:],
                                   all_tokens[:,1,:],
                                   all_tokens[:,2,:])

both does not work?

Thanks again.
Rabab
